name: Build project

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cache ESP-IDF
      id: cache-esp-idf
      uses: actions/cache@v3
      env:
        cache-name: cache-esp-idf
      with:
        path: ${{ github.workspace }}/esp-idf
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Clone ESP-IDF
      if: ${{ steps.cache-esp-idf.outputs.cache-hit != 'true' }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/esp-idf
        repository: espressif/esp-idf
        submodules: recursive

    - name: Cache ESP-IDF tools
      id: cache-esp-idf-tools
      uses: actions/cache@v3
      env:
        cache-name: cache-esp-idf-tools
      with:
        path: ~/.espressif
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Install ESP-IDF
      if: ${{ steps.cache-esp-idf-tools.outputs.cache-hit != 'true' }}
      shell: powershell
      run: |
        cd ${{ github.workspace }}/esp-idf
        ./install.ps1

    - name: Clone copilot
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository_owner }}/copilot
        path: ${{ github.workspace }}/copilot
        submodules: recursive

    - name: Checkout development branch
      run: |
        cd ${{ github.workspace }}/copilot/${{ github.event.repository.name }}
        git checkout ${{ github.head_ref }}

    - name: Cache build
      id: cache-build
      uses: actions/cache@v3
      env:
        cache-name: cache-build
      with:
        path: ${{ github.workspace }}/copilot/${{ github.event.repository.name }}/build
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Build project
      shell: powershell
      run: |
        cd ${{ github.workspace }}/copilot
        ${{ github.workspace }}/esp-idf/export.ps1
        idf.py build
